### ISSUE TITLE
Migration failure causes non-HA data volumes to have multiple LVs

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#1228] opened 2023-11-07 07:40 UTC
![企业微信截图_16993424918709](https://github.com/hwameistor/hwameistor/assets/76234281/5094e664-c2ed-4c3b-8c07-99c807493d21)

**Comment by SSmallMonster** [comment] 2023-11-09 11:49
This is caused by the punre failure of old replica. This operation should happen after migration job completed.

But, this should be fixed actually when we recongnized the replica is NotReady for using indeed.

cc @peng9808

**Closed** 2023-11-28 12:35 UTC
Labels: kind/bug
